Add a sniff to avoid public properties
slevomat/coding-standard pull request #1103
Opened 2020-10-14 20:38 UTC by 50bhan

Following this issue #1099.

2020-10-18 16:39 UTC, 50bhan commented
@kukulich Hi, I believe this PR is ready for review. I'd appreciate it if you could check it out. 

P.S. I'm going to prepare seven PRs for new sniffs. I sent four of them already and I need this PR helper for remaining PRs. That's the reason it's more convenient to go with this one first.

2020-10-20 09:44 UTC, kukulich requested changes
Please fix code coverage.

2020-10-20 09:44 UTC, kukulich commented on SlevomatCodingStandard/Helpers/StructureMetricHelper.php
> +	public static function getFunctionLengthInLines(File $file, int $position): int
Please move method to `FunctionHelper`.

2020-10-20 09:44 UTC, kukulich commented on SlevomatCodingStandard/Helpers/StructureMetricHelper.php
> +		if (!isset($token['scope_opener'])) {
Use `FunctionHelper::isAbstract()`

2020-10-20 09:44 UTC, kukulich commented on SlevomatCodingStandard/Sniffs/Files/FunctionLengthSniff.php
> +	private const ERROR_MESSAGE = 'Your function is too long. Currently using %d lines. Can be up to %d lines.';
Useless constant.

2020-10-20 09:44 UTC, kukulich commented on SlevomatCodingStandard/Sniffs/Files/FunctionLengthSniff.php
> +	 * @return int[]
Please use `array<int, (int|string)>`

2020-10-20 09:44 UTC, kukulich commented on SlevomatCodingStandard/Sniffs/Files/FunctionLengthSniff.php
> +	 * @param int $position
`$functionPointer`

2020-10-20 09:44 UTC, kukulich commented on SlevomatCodingStandard/Sniffs/Files/FunctionLengthSniff.php
> +		if ($length <= $this->maxLength) {
Use `SniffSettingsHelper::normalizeInteger()`

2020-10-20 09:44 UTC, kukulich commented on README.md
> +* `maxLength`: specifies max allowed function length (default value is 20).
Please `maxLinesLength`

2020-10-20 13:42 UTC, merged