Make sure we have a classPointer to fetch a token for
slevomat/coding-standard pull request #1169
Opened 2021-02-24 12:16 UTC by StijnVrolijk

When `ClassHelper::getClassPointer` returns `null`, the next statement would fail because we would attempt to fetch `$tokens[null]`.

2021-02-24 12:22 UTC, kukulich requested changes
I don't see any test case for this situation.

2021-02-25 10:09 UTC, StijnVrolijk commented
The code that led me to this issue was the following (trimmed to the most basic example):

errorfile.php
```php
<?php

namespace Foo;

class Bar
{
    public function lorem(): void
    {
        function ipsum(): void
        {
            // This nested function causes an exception
        }
    }
}
```

ruleset.xml
```xml
<?xml version="1.0"?>
<ruleset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="vendor/squizlabs/php_codesniffer/phpcs.xsd">
    <rule ref="SlevomatCodingStandard.Classes.MethodSpacing" />
</ruleset>
```

command
```bash
phpcs --standard=ruleset.xml errorfile.php
```

I know nested functions are a big no no but it is valid PHP. I just found this piece of code in an old project I've been attempting to clean up.

Anyway, this causes an undefined index error on SlevomatCodingStandard/Sniffs/Classes/MethodSpacingSniff.php:61.

If you would run MethodSpacingSniff through a static analysis tool like PHPStan or psalm it would tell you about this issue. `ClassHelper::getClassPointer` returns `int|null` but on the next line it is used like it's always `int`. By aborting if the pointer is `null` this error gets prevented.

2021-02-25 10:11 UTC, kukulich commented
@StijnVrolijk So just write test please :)

2021-02-25 15:35 UTC, StijnVrolijk commented
Ah sorry, I misunderstood. I've looked at the tests and unfortunately my time/skill is lacking so I won't be able to write a test for this. Feel free to close this PR, I just wanted to let you know about this :)

2021-02-25 15:38 UTC, kukulich commented
Ok, closing because there are not tests.

2021-02-25 15:38 UTC, closed without merging