AttributeSpacingSniff
slevomat/coding-standard pull request #1449
Opened 2022-10-14 13:25 UTC by michnovka

2022-10-14 13:38 UTC, michnovka commented
@kukulich I dont think I can really improve the indentation efficiently. There is just not "correct" way of doing it, this should be enforced using other sniffs. What further complicates things is that we register the sniff on `T_ATTRIBUTE` so when I fix one attribute, I have now inconsistent actual fixed file with tokens from phpcs, as those point to the original parsed file.

I do not have more time to work on this, I am happy with the sniff as is. If you have some more suggestions, let me know.

2022-10-14 13:51 UTC, kukulich commented
@michnovka I really don't understand why the sniff is done differently than suggested in https://github.com/slevomat/coding-standard/issues/1442#issuecomment-1276112153

2022-10-14 14:20 UTC, michnovka commented
when implementing this I was facing some difficulties. Manily due to fixer and the fact this sniff targets `T_ATTRIBUTE`. By the time I fixed one attribute (e.g. add new line after it) it would modify the file for the 2nd one following and suddenly the tokens from phpcsfile were outdated (not corresponding to the fix-in-progress file). I couldnt make it work, so I asked myself the question - whats is the main purpose of this sniff? And that is to not allow having multiple attributes on one line. So thats what I implemented.

I am happy with renaming the sniff to `RequireAttributeOnDedicatedLine` but without targetting directly `AttributeHelper::attributableTokens` instead of T_ATTRIBUTEs I have hard time making it work as in the original comment.

2022-10-14 14:32 UTC, kukulich commented
> I am happy with renaming the sniff to RequireAttributeOnDedicatedLine

I'm not. That's not what I suggested.

2022-10-14 15:29 UTC, michnovka commented
Another issue is mixing of phpdoc and attributes. How to handle spacing there in regards to `linesCountBetweenAttributes`?

This sniff makes sure that attributes are always the only thing on a line. There is an exception for single in-line attributes

2022-10-14 19:32 UTC, michnovka commented
@kukulich I have edited this PR based on https://github.com/slevomat/coding-standard/issues/1442#issuecomment-1279341581 Please review

2022-10-14 20:03 UTC, kukulich requested changes

2022-10-14 20:03 UTC, kukulich commented on SlevomatCodingStandard/Sniffs/Attributes/DisallowMultipleAttributesPerLineSniff.php
> +				'Attribute is not alone on line',
`Multiple attributes per line are disallowed.`

2022-10-14 20:14 UTC, michnovka commented on tests/Sniffs/Attributes/data/disallowedMultipleAttributesPerLineErrors.fixed.php
> +// comment
@kukulich is there some helper function similar to `TokenHelper::findFirstNonWhitespaceOnLine()` that would look for non-whitespace AND non-comment?

2022-10-14 20:16 UTC, kukulich commented on tests/Sniffs/Attributes/data/disallowedMultipleAttributesPerLineErrors.fixed.php
> +// comment
You can just check if there's another `T_ATTRIBUTE` on the same line before current attribute.

2022-10-14 20:47 UTC, michnovka commented on tests/Sniffs/Attributes/data/disallowedMultipleAttributesPerLineErrors.fixed.php
> +// comment
no, I cannot. imagine:

```php
#[Attribute1]
#[Attribute2] /** whatever */ public int $x;
```

2022-10-14 20:51 UTC, kukulich commented on tests/Sniffs/Attributes/data/disallowedMultipleAttributesPerLineErrors.fixed.php
> +// comment
I don't see any problem.

2022-10-14 20:55 UTC, michnovka commented on tests/Sniffs/Attributes/data/disallowedMultipleAttributesPerLineErrors.fixed.php
> +// comment
it should be fixed into
```php
#[Attribute1]
#[Attribute2] /** whatever */
public int $x;
```

the point of this sniff is to have on one line ONLY one attribute AND whitespaces OR comments. But OK, we can make this sniff ONLY about 2 attributes on one line and make another sniff which disallows having attribute and attributed token on the same line. WDYT?

2022-10-14 21:01 UTC, kukulich commented on tests/Sniffs/Attributes/data/disallowedMultipleAttributesPerLineErrors.fixed.php
> +// comment
> make another sniff which disallows having attribute and attributed token on the same line. WDYT?

That's the sniff that should solve number of lines between last attribute and owner (or comment).

2022-10-15 09:00 UTC, michnovka commented on tests/Sniffs/Attributes/data/disallowedMultipleAttributesPerLineErrors.fixed.php
> +// comment
> That's the sniff that should solve number of lines between last attribute and owner (or comment).
How would you call that sniff?

2022-10-15 11:08 UTC, kukulich commented on tests/Sniffs/Attributes/data/disallowedMultipleAttributesPerLineErrors.fixed.php
> +// comment
https://github.com/slevomat/coding-standard/commit/3b165784080535b827f6fa5c311d23d64fe38b7f

2022-10-16 08:48 UTC, kukulich approved these changes

2022-10-16 08:48 UTC, merged

2022-10-16 08:49 UTC, kukulich commented
@michnovka Thanks! I've finished the sniff by myself.