Add support for enforcing leading ternary operators
slevomat/coding-standard pull request #1491
Opened 2023-01-11 10:55 UTC by esserj

Add support to enforce that operators lead when using multi-line ternary operators

2023-01-16 15:23 UTC, kukulich commented
"Naming is hard"

After some dicuss with my colleagues we would prefer `DisableTrailingMultiLineTernaryOperatorSniff` :)

2023-01-16 15:24 UTC, esserj commented
Hi @kukulich,

It is sure it.
But I also like the new name a lot more!
I'll adjust is shortly

2023-01-16 15:39 UTC, esserj commented
@kukulich I've changed it, but I did notice that that are many other rules that use the term disallow
Would you guys agree that it would be more concise to use that instead?

2023-01-17 07:53 UTC, esserj commented
No worries @kukulich.
This should do it!

Thank you for your time!

2023-01-21 08:27 UTC, kukulich requested changes
Please do some minor changes and add missing tests.

2023-01-21 08:27 UTC, kukulich commented on README.md
> + - [SlevomatCodingStandard.ControlStructures.DisAllowTrailingMultiLineTernaryOperatorSniff](doc/control-structures.md#slevomatcodingstandardcontrolstructuresdisallowtrailingmultilineternaryoperator-)
Typo. `Disallow` please.

2023-01-21 08:27 UTC, kukulich commented on SlevomatCodingStandard/Sniffs/ControlStructures/DisallowTrailingMultiLineTernaryOperatorSniff.php
> +	private const TAB_INDENT = "\t";
We can use `IndentationHelper::TAB_INDENT`

2023-01-21 08:27 UTC, kukulich commented on doc/control-structures.md
> +
This line should not be in the diff.

2023-01-30 10:00 UTC, kukulich commented
@esserj Can you please enable access to your repository for me? I'm not able to rebase and push.

2023-01-30 12:40 UTC, esserj commented
@kukulich "allow maintainers to edit" doesnt seems to be available for the organisation account. Not sure why. I've added you with write access. Should be the same I assume?

2023-01-30 12:47 UTC, kukulich approved these changes

2023-01-30 12:51 UTC, kukulich commented
Thanks!

2023-01-30 12:51 UTC, merged

2023-01-30 12:51 UTC, esserj commented
Thanks for your time @kukulich !